import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowRight, BadgeCheck, Building2, Check, CircleAlert, ClipboardList, Fan, HardHat, House, Lightbulb, Menu, MessageCircle, Phone, PlugZap, ShieldCheck, Sparkles, Star, ThumbsUp, Wrench, X, Zap } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { business, businessImages, businessReviews, phoneHref, serviceAreas, whatsappHref } from './config/business'
import './App.css'

type Service = { title: string; description: string; icon: LucideIcon }
const services: Service[] = [
  { title: 'Electrical Repair', description: 'Practical troubleshooting for everyday electrical problems at home or work.', icon: Wrench },
  { title: 'Home Wiring', description: 'Organised wiring support for homes, renovations and new electrical points.', icon: House },
  { title: 'New House Wiring', description: 'Plan and install electrical wiring for new residential spaces.', icon: PlugZap },
  { title: 'Switch & Socket Installation', description: 'Replace, install or reposition switches and sockets neatly.', icon: Lightbulb },
  { title: 'Fan Installation & Repair', description: 'Ceiling fan installation and help with common fan issues.', icon: Fan },
  { title: 'Light Installation', description: 'Install practical lighting for rooms, shops, offices and work areas.', icon: Sparkles },
  { title: 'MCB / DB Installation', description: 'Support for MCB and distribution board installation work.', icon: ShieldCheck },
  { title: 'Short Circuit Troubleshooting', description: 'Trace electrical faults and discuss the right repair approach.', icon: Zap },
  { title: 'Earthing Work', description: 'Electrical earthing work for safer, more reliable installations.', icon: BadgeCheck },
  { title: 'Inverter Wiring', description: 'Connect inverter wiring for residential electrical setups.', icon: PlugZap },
  { title: 'Geyser Electrical Connection', description: 'Electrical connection support for geysers and related appliances.', icon: Zap },
  { title: 'Shop & Office Electrical Work', description: 'Electrical repair and installation support for local businesses.', icon: Building2 },
]
const navItems = [['Services', '#services'], ['About', '#about'], ['Our Work', '#work'], ['Reviews', '#reviews'], ['Contact', '#contact']]
const benefits: [string, string, LucideIcon][] = [
  ['Professional Service', 'A practical, respectful approach to every job.', HardHat],
  ['Local Nagpur Support', 'Service focused on Nagpur and nearby areas.', House],
  ['Clear Communication', 'Understand the issue and the work involved.', ThumbsUp],
  ['Repair & Installation', 'Support for repairs, wiring and installations.', Wrench],
  ['Residential & Commercial', 'For homes, shops, offices and other properties.', Building2],
  ['Safety-Focused Work', 'Careful attention to electrical safety.', ShieldCheck],
]

function ActionLink({ kind, children, className = '', icon = true, ariaLabel }: { kind: 'phone' | 'whatsapp'; children: ReactNode; className?: string; icon?: boolean; ariaLabel?: string }) {
  const href = kind === 'phone' ? phoneHref : whatsappHref()
  const Icon = kind === 'phone' ? Phone : MessageCircle
  const content = <>{icon && <Icon size={17} />}{children}</>
  if (!href) return <button className={`${className} action-disabled`} type="button" aria-label={ariaLabel} title={`Add the ${kind} number in src/config/business.ts`}>{content}</button>
  return <a className={className} href={href} aria-label={ariaLabel} target={kind === 'whatsapp' ? '_blank' : undefined} rel={kind === 'whatsapp' ? 'noreferrer' : undefined}>{content}</a>
}

const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'Electrician',
  name: business.name,
  founder: business.owner,
  telephone: business.phone,
  areaServed: `${business.city}, ${business.state}, ${business.country}`,
  url: business.websiteUrl,
  sameAs: [business.googleProfile1, business.googleProfile2],
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [selectedService, setSelectedService] = useState('')
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }

  return <div className="site-shell">
    <script type="application/ld+json">{JSON.stringify(localBusinessSchema)}</script><header className="navbar"><a className="brand" href="#home" aria-label="Sachin Electrician Services home"><span className="brand-mark"><Zap size={22} fill="currentColor" /></span><span><strong>Sachin</strong> Electrician</span></a><nav className={menuOpen ? 'nav-links open' : 'nav-links'} aria-label="Primary navigation">{navItems.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="nav-actions"><ActionLink kind="phone" className="button button-dark">Call Now</ActionLink><ActionLink kind="phone" className="nav-call-mobile" ariaLabel="Call Sachin"><Phone size={18} /></ActionLink><button className="menu-button" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></div></header>
    <main>
      <section id="home" className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Local electrician services in Nagpur</p><h1>Reliable electrical services <em>in Nagpur.</em></h1><p className="hero-lead">Professional electrical repair, wiring, installation and maintenance for homes, shops and offices across Nagpur.</p><div className="hero-actions"><ActionLink kind="phone" className="button button-yellow">Call Sachin <ArrowRight size={17} /></ActionLink><ActionLink kind="whatsapp" className="button button-outline">WhatsApp <MessageCircle size={17} /></ActionLink></div><a className="text-link" href="#contact">Request a service <ArrowRight size={16} /></a><div className="hero-location"><span className="location-pin">⌖</span> Serving Nagpur & nearby areas</div></div><div className="hero-photo">{businessImages.hero ? <img src={businessImages.hero} alt={businessImages.heroImageAlt} fetchPriority="high" /> : <div className="photo-placeholder hero-placeholder"><PlugZap size={45} /><span>REAL HERO PHOTO<br /><small>Replace in businessImages.hero</small></span></div>}</div></section>
      <section className="trust-bar" aria-label="Service highlights">{[['Local Nagpur Service', House], ['Residential & Commercial', Building2], ['Repair & Installation', Wrench], ['Quick Response', Zap]].map(([label, Icon]) => <div className="trust-item" key={label as string}><Icon size={19} /><span>{label as string}</span></div>)}</section>
      <section id="services" className="section services-section"><div className="section-heading"><div><p className="eyebrow">What we do</p><h2>Electrical services you can rely on.</h2></div><p>From electrical repair in Nagpur to complete wiring work, get practical support for your property.</p></div><div className="service-grid">{services.map(({ title, description, icon: Icon }) => <article className="service-card" key={title}><div className="card-icon"><Icon size={21} /></div><h3>{title}</h3><p>{description}</p><a href="#contact" onClick={() => setSelectedService(title)}>Enquire now <ArrowRight size={15} /></a></article>)}</div><div className="featured-service"><div className="featured-icon"><CircleAlert size={23} /></div><div><p className="eyebrow">Not sure what you need?</p><h3>Describe the problem.</h3><p>Get help choosing the right electrical service. Tell us what is happening and share a photo if useful.</p></div><a className="button button-dark" href="#contact">Describe your problem <ArrowRight size={16} /></a></div></section>
      <section className="urgent-section"><div className="urgent-icon"><CircleAlert size={29} /></div><div><p className="eyebrow eyebrow-light">Urgent electrical help</p><h2>Having an electrical problem?</h2><p>From power failures and MCB issues to switchboard, fan, lighting and wiring problems, get in touch.</p></div><ActionLink kind="phone" className="button button-yellow">Call Sachin <ArrowRight size={17} /></ActionLink></section>
      <section className="section why-section"><div className="why-intro"><p className="eyebrow">Why Sachin</p><h2>Good electrical work starts with good communication.</h2><p>A local service should feel straightforward. Share the problem, understand the work, and make the next decision with clarity.</p><a className="text-link" href="#contact">Start a conversation <ArrowRight size={16} /></a></div><div className="benefit-grid">{benefits.map(([title, copy, Icon]) => <div className="benefit" key={title}><Icon size={20} /><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section>
      <section id="about" className="about-section"><div className="about-photo">{businessImages.about ? <img src={businessImages.about} alt="Sachin Nimbekar, electrician in Nagpur" loading="lazy" decoding="async" /> : <div className="photo-placeholder"><HardHat size={54} /><span>REAL PROFILE PHOTO<br /><small>Replace in businessImages.about</small></span></div>}<div className="portrait-caption"><span>LOCAL ELECTRICIAN • NAGPUR</span><strong>{business.owner}</strong></div></div><div className="about-copy"><p className="eyebrow">About Sachin</p><h2>Meet Sachin Nimbekar.</h2><p>{business.owner} provides electrical services in {business.city} and nearby areas, helping customers with electrical repairs, installations, wiring and maintenance.</p><div className="about-checks"><span><Check size={15} /> Professional electrical service</span><span><Check size={15} /> Local Nagpur support</span><span><Check size={15} /> Repair & installation</span><span><Check size={15} /> Residential & commercial work</span></div></div></section>
      <section id="work" className="section work-section"><div className="section-heading"><div><p className="eyebrow">Our work</p><h2>Electrical Work, Done Right.</h2></div><p>A look at some of the electrical installation, repair and maintenance work Sachin handles for homes and businesses.</p></div><div className="work-grid">{businessImages.gallery.map((item, index) => <article className={`work-card work-${index + 1}`} key={item.title}>{item.image ? <img src={item.image} alt={item.alt} loading="lazy" decoding="async" style={{ objectPosition: item.objectPosition }} /> : <div className="work-placeholder"><span>PHOTO PLACEHOLDER</span><Wrench size={28} /></div>}<div className="work-label"><strong>{item.title}</strong><span>{item.category}</span></div></article>)}</div><div className="gallery-cta"><div><h3>Need similar electrical work?</h3><p>Tell Sachin what you need help with.</p></div><a className="button button-dark" href="#contact">Request service <ArrowRight size={16} /></a></div></section>
      <section id="reviews" className="reviews-section"><div className="reviews-heading"><div className="reviews-mark"><Star size={25} /></div><div><p className="eyebrow">Customer reviews</p><h2>What our customers say.</h2><p>See what customers have to say about electrical services from Sachin Nimbekar.</p></div></div>{businessReviews.length > 0 ? <div className="review-grid">{businessReviews.map((review) => <article className="review-card" key={`${review.author}-${review.text}`}><div className="review-stars" aria-label={`${review.rating} out of 5 stars`}>{'★'.repeat(review.rating)}</div><p>“{review.text}”</p><strong>{review.author}</strong><span>{review.source} Review</span></article>)}</div> : <div className="reviews-empty"><div className="empty-icon"><MessageCircle size={21} /></div><div><h3>Real customer reviews will appear here.</h3><p>Check Sachin’s Google profile for the latest customer feedback.</p></div><a className="button button-dark" href={business.googleProfile1} target="_blank" rel="noopener noreferrer">See all reviews on Google <ArrowRight size={16} /></a></div>}</section>
      <section className="areas-section"><div className="areas-intro"><p className="eyebrow">Service areas</p><h2>Electrical services across Nagpur.</h2><p>From Pardi to Hingna and across major residential and commercial areas of Nagpur, Sachin provides electrical repair, wiring, installation and maintenance services.</p><div className="area-trust-line"><Check size={15} /> Serving homes, shops and offices across Nagpur.</div></div><div className="coverage-visual" aria-label="Representative service coverage from Pardi through Central Nagpur to Hingna"><div className="coverage-label"><House size={18} /><span>Nagpur<br /><strong>service coverage</strong></span></div><div className="coverage-route"><div className="coverage-node"><span className="coverage-dot" /><strong>Pardi</strong></div><div className="coverage-line" /><div className="coverage-node coverage-node-center"><span className="coverage-dot" /><strong>Central Nagpur</strong></div><div className="coverage-line" /><div className="coverage-node coverage-node-end"><span className="coverage-dot" /><strong>Hingna</strong></div></div><p className="coverage-note">Representative coverage, not an exact boundary</p></div><div className="areas-directory"><div className="directory-heading"><div><p className="eyebrow">Areas we serve</p><h3>Local electrical help when you need it.</h3></div><p>Coverage may vary by location. Call Sachin to confirm availability.</p></div><div className="area-groups">{serviceAreas.map((area) => <div className="area-group" key={area.group}><h4>{area.group}</h4><div className="area-chips">{area.areas.map((name) => <span className="area-chip" key={name}><span>⌖</span>{name}</span>)}</div></div>)}</div><div className="area-cta"><div><p className="area-question">Not sure if your location is covered?</p><strong>Call Sachin to confirm service availability.</strong></div><div className="area-cta-actions"><ActionLink kind="phone" className="button button-yellow">Call Sachin <ArrowRight size={17} /></ActionLink><ActionLink kind="whatsapp" className="button button-outline">WhatsApp <MessageCircle size={17} /></ActionLink></div></div></div></section>
      <section id="contact" className="contact-section"><div className="contact-intro"><p className="eyebrow eyebrow-light">Get in touch</p><h2>Need an electrician in Nagpur?</h2><p>Tell Sachin what electrical work you need and get in touch directly.</p><div className="contact-options"><ActionLink kind="phone" icon={false} className="contact-option"><span className="contact-option-icon"><Phone size={19} /></span><span><small>Have an electrical problem?</small><strong>Call Sachin</strong><em>Call directly for the quickest conversation.</em></span><ArrowRight size={16} /></ActionLink><ActionLink kind="whatsapp" icon={false} className="contact-option"><span className="contact-option-icon whatsapp-icon"><MessageCircle size={19} /></span><span><small>Prefer WhatsApp?</small><strong>WhatsApp Sachin</strong><em>Send the details of the work you need.</em></span><ArrowRight size={16} /></ActionLink></div></div><div className="form-card">{submitted ? <div className="form-success"><div className="success-icon"><Check /></div><h3>Request prepared.</h3><p>This frontend form is ready for a backend connection. No request has been sent yet.</p><button className="button button-dark" type="button" onClick={() => setSubmitted(false)}>Prepare another request</button></div> : <form onSubmit={handleSubmit}><div className="form-heading"><span>01 / SERVICE REQUEST</span><h3>Describe the work you need.</h3></div><div className="field-row"><label>Name<input required name="name" placeholder="Your name" /></label><label>Phone number<input required type="tel" name="phone" placeholder="Your phone number" /></label></div><div className="field-row"><label>Location / area<input required name="location" placeholder="e.g. Nagpur" /></label><label>Service required<select required name="service" value={selectedService} onChange={(event) => setSelectedService(event.target.value)}><option value="">Select a service</option>{services.map((service) => <option key={service.title} value={service.title}>{service.title}</option>)}</select></label></div><label>Message / describe the problem<textarea name="message" rows={4} placeholder="Briefly describe the electrical issue..." /></label><label className="file-field">Photo of electrical problem<input type="file" accept="image/*" /></label><button className="button button-yellow submit-button" type="submit">Request service <ArrowRight size={17} /></button><p className="form-note"><ClipboardList size={14} /> Please note: this form prepares your enquiry. For a faster response, call or WhatsApp Sachin directly.</p></form>}</div></section>
    </main>
    <footer className="footer"><div className="footer-top"><div><a className="brand brand-footer" href="#home"><span className="brand-mark"><Zap size={20} fill="currentColor" /></span><span><strong>Sachin</strong> Electrician</span></a><p>Professional electrical services<br />in Nagpur.</p></div><div className="footer-links"><strong>Explore</strong>{navItems.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div><div className="footer-links"><strong>Connect</strong><ActionLink kind="phone">Call now</ActionLink><ActionLink kind="whatsapp">WhatsApp</ActionLink><a href={business.googleProfile1} target="_blank" rel="noreferrer">Google Business Profile</a></div></div><div className="footer-bottom"><span>© 2026 {business.name}. All rights reserved.</span><span>Nagpur, Maharashtra, India</span><span aria-hidden="true">●</span></div></footer>
    <div className="mobile-contact-bar"><ActionLink kind="phone"><Phone size={18} /> Call</ActionLink><ActionLink kind="whatsapp"><MessageCircle size={18} /> WhatsApp</ActionLink></div>
  </div>
}

export default App
